spring:
  config:
    activate:
      on-profile: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 217844333464-e8mpaqbg7cgsm0v7db42oqkbffonqthg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
          kakao:
            client-name: kakao
            client-id: 326f5c4c2ca1457d9c6c12db344b79f8
            scope:
              - account_email
              - profile_nickname
              - profile_image
            authorization-grant-type: authorization_code
          naver:
            client-name: naver
            client-id: M_iZwU3wZ8Ip2qHAFWP6
            client-secret: rF3TGRDc9S
            scope:
              - email
              - name
              - profile_image
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response