spring:
  config:
    activate:
      on-profile: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth.google.client-id}
            client-secret: ${oauth.google.client-secret}
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
          kakao:
            client-name: kakao
            client-id: ${oauth.kakao.client-id}
            scope:
              - account_email
              - profile_nickname
              - profile_image
            authorization-grant-type: authorization_code
          naver:
            client-name: naver
            client-id: ${oauth.naver.client-id}
            client-secret: ${oauth.naver.client-secret}
            scope:
              - email
              - name
              - profile_image
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: ${oauth.kakao.authorization-uri}
            token-uri: ${oauth.kakao.token-uri}
            user-info-uri: ${oauth.kakao.user-info-uri}
            user-name-attribute: ${oauth.kakao.name-attribute}
          naver:
            authorization-uri: ${oauth.naver.authorization-uri}
            token-uri: ${oauth.naver.token-uri}
            user-info-uri: ${oauth.naver.user-info-uri}
            user-name-attribute: ${oauth.naver.name-attribute}