apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: dev
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
    - port: 15601
      targetPort: 5601

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:9.0.2
          ports:
            - containerPort: 5601
          volumeMounts:
            - name: kibana-configmap-volume
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
      volumes:
        - name: kibana-configmap-volume
          configMap:
            name: kibana-configmap