apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-profile-configmap
      imagePullSecrets:
        - name: ghcr-secret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
        - name: auth-service
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-profile-configmap
      imagePullSecrets:
        - name: ghcr-secret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
spec:
  template:
    spec:
      containers:
        - name: subscription-service
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-profile-configmap
      imagePullSecrets:
        - name: ghcr-secret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  template:
    spec:
      containers:
        - name: ai-service
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-profile-configmap
      imagePullSecrets:
        - name: ghcr-secret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
spec:
  template:
    spec:
      containers:
        - name: document-service
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-profile-configmap
      imagePullSecrets:
        - name: ghcr-secret