services:
  api-gateway:
    build:
      dockerfile: api-gateway/Dockerfile
      context: .
    image: brieflyz/api-gateway:latest
    container_name: api-gateway
    scale: 1
    ports:
      - "8000"
    environment:
      APPLICATION_PROFILE: dev
    volumes:
      - log-volume:/app/logs
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8000/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    depends_on:
      - auth-service
    restart: on-failure
    networks:
      - brieflyz-network

  auth-service:
    build:
      dockerfile: auth-service/Dockerfile
      context: .
    image: brieflyz/auth-service:latest
    container_name: auth-service
    scale: 1
    ports:
      - "8090"
    environment:
      APPLICATION_PROFILE: dev
      TZ: Asia/Seoul
    volumes:
      - log-volume:/app/logs
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8090/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: on-failure
    networks:
      - brieflyz-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway
    restart: always
    networks:
      - brieflyz-network

  zookeeper-0:
    image: zookeeper:latest
    container_name: zookeeper-0
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper-0:2888:3888;2181 server.2=zookeeper-1:2888:3888;2181 server.3=zookeeper-2:2888:3888;2181
    networks:
      - brieflyz-network

  zookeeper-1:
    image: zookeeper:latest
    container_name: zookeeper-1
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper-0:2888:3888;2181 server.2=zookeeper-1:2888:3888;2181 server.3=zookeeper-2:2888:3888;2181
    networks:
      - brieflyz-network

  zookeeper-2:
    image: zookeeper:latest
    container_name: zookeeper-2
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper-0:2888:3888;2181 server.2=zookeeper-1:2888:3888;2181 server.3=zookeeper-2:2888:3888;2181
    networks:
      - brieflyz-network

  kafka-0:
    image: wurstmeister/kafka:latest
    container_name: kafka-0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-0:2181,zookeeper-1:2182,zookeeper-2:2183
      KAFKA_LISTENERS: INTERNAL://kafka-0:19092,EXTERNAL://kafka-0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-0:19092,EXTERNAL://kafka-0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    ports:
      - "9092:9092"
      - "19092:19092"
    depends_on:
      - zookeeper-0
      - zookeeper-1
      - zookeeper-2
    networks:
      - brieflyz-network

  kafka-1:
    image: wurstmeister/kafka:latest
    container_name: kafka-1
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-0:2181,zookeeper-1:2182,zookeeper-2:2183
      KAFKA_LISTENERS: INTERNAL://kafka-1:19093,EXTERNAL://kafka-1:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19093,EXTERNAL://kafka-1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    ports:
      - "9093:9093"
      - "19093:19093"
    depends_on:
      - zookeeper-0
      - zookeeper-1
      - zookeeper-2
    networks:
      - brieflyz-network

  kafka-2:
    image: wurstmeister/kafka:latest
    container_name: kafka-2
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-0:2181,zookeeper-1:2182,zookeeper-2:2183
      KAFKA_LISTENERS: INTERNAL://kafka-2:19094,EXTERNAL://kafka-2:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:19094,EXTERNAL://kafka-2:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    ports:
      - "9094:9094"
      - "19094:19094"
    depends_on:
      - zookeeper-0
      - zookeeper-1
      - zookeeper-2
    networks:
      - brieflyz-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "10000:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-0:9092,kafka-1:9093,kafka-2:9094
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    restart: always
    networks:
      - brieflyz-network

  mysql-source:
    image: mysql:latest
    container_name: mysql-source
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "13306:3306"
    volumes:
      - ./conf/mysql/my-source.cnf:/etc/mysql/my.cnf
      - mysql-source-volume:/var/lib/mysql
    networks:
      - brieflyz-network

  mysql-replica:
    image: mysql:latest
    container_name: mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "23306:3306"
    volumes:
      - ./conf/mysql/my-replica.cnf:/etc/mysql/my.cnf
      - mysql-replica-volume:/var/lib/mysql
    depends_on:
      - mysql-source
    networks:
      - brieflyz-network

  redis-0:
    image: redis:latest
    container_name: redis-0
    ports:
      - "6379:6379"
      - "16379:16379"
    command: redis-server /etc/redis.conf
    volumes:
      - ./conf/redis/redis-0.conf:/etc/redis.conf
    restart: always
    networks:
      - brieflyz-network

  redis-1:
    image: redis:latest
    container_name: redis-1
    ports:
      - "6380:6379"
      - "16380:16379"
    command: redis-server /etc/redis.conf
    volumes:
      - ./conf/redis/redis-1.conf:/etc/redis.conf
    restart: always
    networks:
      - brieflyz-network

  redis-2:
    image: redis:latest
    container_name: redis-2
    ports:
      - "6381:6379"
      - "16381:16379"
    command: redis-server /etc/redis.conf
    volumes:
      - ./conf/redis/redis-2.conf:/etc/redis.conf
    restart: always
    networks:
      - brieflyz-network

  es-monitoring:
    image: elasticsearch:9.0.2
    container_name: es-monitoring
    ports:
      - "19200:9200"
      - "19300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - ./conf/elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - es-volume:/usr/share/elasticsearch/data
    networks:
      - brieflyz-network

  kibana:
    image: kibana:9.0.2
    container_name: kibana
    ports:
      - "15601:5601"
    volumes:
      - ./conf/elk/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - es-monitoring
    networks:
      - brieflyz-network

  logstash:
    image: logstash:9.0.2
    container_name: logstash
    ports:
      - "5044"
    volumes:
      - ./conf/elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    depends_on:
      - es-monitoring
    networks:
      - brieflyz-network

  filebeat:
    image: elastic/filebeat:9.0.2
    container_name: filebeat
    user: root
    volumes:
      - ./conf/elk/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - log-volume:/logs:ro
    depends_on:
      - logstash
    networks:
      - brieflyz-network

#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    ports:
#      - "19090:9090"
#    volumes:
#      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    networks:
#      - brieflyz-network
#
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - "13000:3000"
#    networks:
#      - brieflyz-network

volumes:
  mysql-source-volume:
  mysql-replica-volume:
  es-volume:
  log-volume:

networks:
  brieflyz-network: