services:
  mysql-source:
    image: mysql:latest
    container_name: mysql-source
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "13306:3306"
    volumes:
      - ./conf/mysql/my-source.cnf:/etc/mysql/my.cnf
      - mysql-source-volume:/var/lib/mysql
    networks:
      - brieflyz-network

  mysql-replica:
    image: mysql:latest
    container_name: mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "23306:3306"
    volumes:
      - ./conf/mysql/my-replica.cnf:/etc/mysql/my.cnf
      - mysql-replica-volume:/var/lib/mysql
    depends_on:
      - mysql-source
    networks:
      - brieflyz-network

  redis-0:
    image: redis:latest
    container_name: redis-0
    ports:
      - "6379:6379"
      - "16379:16379"
    command: redis-server /etc/redis.conf
    volumes:
      - ./conf/redis/redis-0.conf:/etc/redis.conf
    restart: always
    networks:
      - brieflyz-network

  redis-1:
    image: redis:latest
    container_name: redis-1
    ports:
      - "6380:6379"
      - "16380:16379"
    command: redis-server /etc/redis.conf
    volumes:
      - ./conf/redis/redis-1.conf:/etc/redis.conf
    restart: always
    networks:
      - brieflyz-network

  redis-2:
    image: redis:latest
    container_name: redis-2
    ports:
      - "6381:6379"
      - "16381:16379"
    command: redis-server /etc/redis.conf
    volumes:
      - ./conf/redis/redis-2.conf:/etc/redis.conf
    restart: always
    networks:
      - brieflyz-network

volumes:
  mysql-source-volume:
  mysql-replica-volume:

networks:
  brieflyz-network: