services:
  elasticsearch:
    image: elasticsearch:9.0.2
    container_name: elasticsearch
    ports:
      - "19200:9200"
      - "19300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - ./conf/elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - es-volume:/usr/share/elasticsearch/data
    networks:
      - brieflyz-network

  kibana:
    image: kibana:9.0.2
    container_name: kibana
    ports:
      - "15601:5601"
    volumes:
      - ./conf/elk/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - brieflyz-network

  logstash:
    image: logstash:9.0.2
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./conf/elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    depends_on:
      - elasticsearch
    networks:
      - brieflyz-network

  filebeat:
    image: elastic/filebeat:9.0.2
    container_name: filebeat
    user: root
    volumes:
      - ./conf/elk/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - log-volume:/logs:ro
    depends_on:
      - logstash
    networks:
      - brieflyz-network

#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    ports:
#      - "19090:9090"
#    volumes:
#      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    networks:
#      - brieflyz-network
#
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - "13000:3000"
#    networks:
#      - brieflyz-network

volumes:
  es-volume:
  log-volume:

networks:
  brieflyz-network: