services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway
    restart: always
    networks:
      - brieflyz-network

  api-gateway:
    build:
      dockerfile: api-gateway/Dockerfile
      context: .
    image: brieflyz/api-gateway:latest
    scale: 1
    ports:
      - "8000"
    environment:
      APPLICATION_PROFILE: dev
    volumes:
      - log-volume:/app/logs
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8000/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: on-failure
    networks:
      - brieflyz-network

  auth-service:
    build:
      dockerfile: auth-service/Dockerfile
      context: .
    image: brieflyz/auth-service:latest
    scale: 1
    ports:
      - "8090"
    environment:
      APPLICATION_PROFILE: dev
      TZ: Asia/Seoul
    volumes:
      - log-volume:/app/logs
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8090/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: on-failure
    networks:
      - brieflyz-network

volumes:
  log-volume:

networks:
  brieflyz-network: