server:
  port: 8000
spring:
  application:
    name: api-gateway
  profiles:
    active: ${APPLICATION_PROFILE:local}
---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: auth-service-authentication
              uri: http://localhost:8090
              predicates:
                - Path=/api/auth/**,/oauth2/authorization/**
            - id: auth-service-members
              uri: http://localhost:8090
              predicates:
                - Path=/api/members/**
              filters:
                - AuthorizationHeaderFilter
            - id: subscription-service
              uri: http://localhost:8070
              predicates:
                - Path=/api/subscriptions/**,/api/admin/subscriptions/**
              filters:
                - AuthorizationHeaderFilter
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: auth-service-authentication
              uri: http://auth-service:8090
              predicates:
                - Path=/api/auth/**,/oauth2/authorization/**,/login/oauth2/code/**
            - id: auth-service-members
              uri: http://auth-service:8090
              predicates:
                - Path=/api/members/**
              filters:
                - AuthorizationHeaderFilter