apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/shared
    server: 192.168.49.2
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-logs-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi