server:
  port: 8070
spring:
  application:
    name: subscription-service
  profiles:
    active: ${APPLICATION_PROFILE:local}
---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/brieflyz?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}