spring:
  application:
    name: subscription-service
  profiles:
    active: ${APPLICATION_PROFILE:local}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        query.in_clause_parameter_padding: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  kafka:
    consumer:
      group-id: subscription-service-group
  data:
    redis:
      connect-timeout: 3000
      timeout: 3000
  mail:
    host: ${gmail.host}
    port: ${gmail.port}
    username: ${gmail.username}
    password: ${gmail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
---
server:
  port: 8070
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    hikari:
      source:
        jdbc-url: jdbc:mysql://${MYSQL_SOURCE_ADDR:localhost:13306}/brieflyz_subscription?createDatabaseIfNotExist=true
        username: ${mysql.username}
        password: ${mysql.root-password}
        pool-name: subscription-service-source-pool
        maximum-pool-size: 3
        minimum-idle: 1
      replica:
        jdbc-url: jdbc:mysql://${MYSQL_REPLICA_ADDR:localhost:23306}/brieflyz_subscription?createDatabaseIfNotExist=true
        username: ${mysql.username}
        password: ${mysql.root-password}
        pool-name: subscription-service-replica-pool
        maximum-pool-size: 5
        minimum-idle: 3
        read-only: true
  data:
    redis:
      cluster:
        nodes: ${REDIS_CLUSTER_NODES:localhost:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9093,localhost:9094}
app:
  subscription:
    kafka:
      num-of-partitions: 9
      replication-factor: 3
---
spring:
  config:
    activate:
      on-profile: dev
    import: configserver:http://config-server:8888/
  cloud:
    config:
      name: subscription-service
      profile: dev