apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: dev
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
    - port: 5044

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:9.0.2
          ports:
            - containerPort: 5044
          env:
            - name: LS_JAVA_OPTS
              value: -Xms256m -Xmx256m
          volumeMounts:
            - name: logstash-configmap-volume
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
      volumes:
        - name: logstash-configmap-volume
          configMap:
            name: logstash-configmap