apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath: # 클러스터 노드 로컬에 저장
    path: /mnt/disks/nfs-server
    type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: nfs-hs
  namespace: dev
  labels:
    app: nfs
spec:
  selector:
    app: nfs
  clusterIP: None
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111

---

apiVersion: v1
kind: Service
metadata:
  name: nfs
  namespace: dev
  labels:
    app: nfs
spec:
  selector:
    app: nfs
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs
  namespace: dev
  labels:
    app: nfs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nfs
  template:
    metadata:
      labels:
        app: nfs
    spec:
      securityContext:
        fsGroup: 65534
      containers:
        - name: nfs
          image: itsthenetwork/nfs-server-alpine:latest
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          env:
            - name: SHARED_DIRECTORY
              value: /exports
          securityContext:
            privileged: true
          volumeMounts:
            - name: nfs-pvc-volume
              mountPath: /exports
      volumes:
        - name: nfs-pvc-volume
          persistentVolumeClaim:
            claimName: nfs-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: dev
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi