server:
  port: 8090
spring:
  application:
    name: user-service
  profiles:
    active: ${APPLICATION_PROFILE:local}
---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false
  r2dbc:
    url: r2dbc:mysql://localhost:3306/brieflyz?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9092
app:
  user:
    kafka:
      num-of-partitions: 1
      replication-factor: 1