apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  template:
    spec:
      containers:
        - name: kafka
  volumeClaimTemplates:
    - metadata:
        name: kafka-volume
      spec:
        storageClassName: standard-rwo
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
spec:
  template:
    spec:
      containers:
        - name: kubernetes-zookeeper
  volumeClaimTemplates:
    - metadata:
        name: zk-volume
      spec:
        storageClassName: standard-rwo
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi