apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/msg

namespace: dev

labels:
  - pairs:
      role: msg
    includeSelectors: true
    includeTemplates: true

replicas:
  - name: kafka
    count: 3
  - name: zk
    count: 3

patches:
  - path: dev-patch.yml