apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
        - name: storage-permission
          image: busybox
          command:
            - sh
            - -c
            - chown -R 472:472 /var/lib/grafana
          volumeMounts:
            - name: grafana-volume
              mountPath: /var/lib/grafana
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-volume
              mountPath: /var/lib/grafana
            - name: grafana-datasource-configmap-volume
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboard-provider-configmap-volume
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboard-json-configmap-volume
              mountPath: /var/lib/grafana/dashboards
          securityContext:
            runAsUser: 472
            runAsGroup: 472
            allowPrivilegeEscalation: false
      volumes:
        - name: grafana-volume
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-datasource-configmap-volume
          configMap:
            name: grafana-datasource-configmap
        - name: grafana-dashboard-provider-configmap-volume
          configMap:
            name: grafana-dashboard-provider-configmap
        - name: grafana-dashboard-json-configmap-volume
          configMap:
            name: grafana-dashboard-json-configmap

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi