apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 8090

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8090"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - auth-service
              weight: 100
      containers:
        - name: auth-service
          image: brieflyz-auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8090
          env:
            - name: APPLICATION_PROFILE
              value: dev
          volumeMounts:
            - name: nfs-logs-pvc-volume
              mountPath: /app/logs
      volumes:
        - name: nfs-logs-pvc-volume
          persistentVolumeClaim:
            claimName: nfs-logs-pvc