apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  labels:
    app: subscription-service
spec:
  selector:
    app: subscription-service
  ports:
    - port: 8070

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
  labels:
    app: subscription-service
spec:
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - subscription-service
              weight: 100
      containers:
        - name: subscription-service
          image: subscription-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8070
          envFrom:
            - configMapRef:
                name: app-profile-configmap
      imagePullSecrets:
        - name: ghcr-secret