apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai-service
  ports:
    - port: 8999

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  selector:
    matchLabels:
      app: ai-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ai-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8999"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ai-service
              weight: 100
      containers:
        - name: ai-service
          image: ai-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8999
          envFrom:
            - configMapRef:
                name: app-profile-configmap
          volumeMounts:
            - name: nfs-logs-pvc-volume
              mountPath: /app/logs
            - name: nfs-documents-pvc-volume
              mountPath: /app/documents
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: nfs-logs-pvc-volume
          persistentVolumeClaim:
            claimName: nfs-logs-pvc
        - name: nfs-documents-pvc-volume
          persistentVolumeClaim:
            claimName: nfs-documents-pvc