apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  clusterIP: None
  ports:
    - port: 6379
      name: client
    - port: 16379
      name: gossip

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis
              weight: 100
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
              name: client
            - containerPort: 16379
              name: gossip
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - redis-server
            - /etc/redis.conf
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis.conf
              subPathExpr: "$(HOSTNAME).conf"
            - name: redis-volume
              mountPath: /data
      volumes:
        - name: redis-config
          configMap:
            name: redis-configmap
  volumeClaimTemplates:
    - metadata:
        name: redis-volume
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi