apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: dev
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: dev
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - api-gateway
      containers:
        - name: api-gateway
          image: brieflyz/api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: APPLICATION_PROFILE
              value: dev
          volumeMounts:
            - name: api-gateway-logs-pvc-volume
              mountPath: /app/logs
      volumes:
        - name: api-gateway-logs-pvc-volume
          persistentVolumeClaim:
            claimName: api-gateway-logs-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-gateway-logs-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi